import streamlit as st
import pandas as pd
import plotly.express as px
from style import *
from utils import * 

# ==========================
# PAGE CONFIG
# ==========================

st.set_page_config(page_title="Sales Overview",page_icon="📊",layout="wide",initial_sidebar_state="expanded")

# ==========================
# STYLE
# ==========================

inject_css()
sidebar_brand()

# ==========================
# LOAD DATA
# ==========================

@st.cache_data
def load_data():
    df=pd.read_csv("data/Walmart.csv")
    df["transaction_date"]=pd.to_datetime(df["transaction_date"])
    return df

df=load_data()
df=sidebar_filters(df)
# ==========================
# REVENUE COLUMN
# ==========================

df["Revenue"]=df["quantity_sold"]*df["unit_price"]

# ==========================
# SUMMARY METRICS
# ==========================

summary={
    "Total Revenue":df["Revenue"].sum(),
    "Total Transactions":df["transaction_id"].nunique() if "transaction_id" in df.columns else len(df),
    "Units Sold":df["quantity_sold"].sum(),
    "Average Order Value":df["Revenue"].sum()/(df["transaction_id"].nunique() if "transaction_id" in df.columns else len(df))
}

# ==========================
# PAGE HEADER
# ==========================

st.title("🏠 Sales Overview")
st.caption("Analyze sales performance, revenue trends, customer demand, and business growth.")

# ==========================
# KPI SECTION
# ==========================

c1,c2,c3,c4=st.columns(4)

kpi_card(c1,"💰 Total Revenue",f"${summary['Total Revenue']:,.0f}",color="green")
kpi_card(c2,"🛒 Transactions",f"{summary['Total Transactions']:,}",color="cyan")
kpi_card(c3,"📦 Units Sold",f"{summary['Units Sold']:,}",color="yellow")
kpi_card(c4,"💳 Avg Order Value",f"${summary['Average Order Value']:,.2f}",color="purple")

st.divider()

# ==========================
# DAILY SALES TREND
# ==========================

section_header("📈 Daily Sales Trend")
chart_label("📌 Total units sold across all transactions over time.")
sales_trend=df.groupby("transaction_date")["quantity_sold"].sum().reset_index()
fig=px.line(sales_trend,x="transaction_date",y="quantity_sold")
apply_plot_layout(fig)
st.plotly_chart(fig,use_container_width=True)
chart_note("💡 Sales trends help identify growth patterns, seasonal fluctuations, and demand shifts.")

# ==========================
# REVENUE TREND
# ==========================

section_header("💰 Revenue Trend")
chart_label("📌 Revenue generated across the analysis period.")
revenue_trend=df.groupby("transaction_date")["Revenue"].sum().reset_index()
fig=px.area(revenue_trend,x="transaction_date",y="Revenue")
apply_plot_layout(fig)
st.plotly_chart(fig,use_container_width=True)
chart_note("💡 Revenue trends provide visibility into business growth and financial performance.")

# ==========================
# CATEGORY ANALYSIS
# ==========================

col1,col2=st.columns(2)

with col1:
    section_header("📦 Category Distribution")
    chart_label("📌 Sales contribution by product category.")
    category_sales=df.groupby("category")["quantity_sold"].sum().reset_index()
    fig=px.pie(category_sales,names="category",values="quantity_sold")
    apply_plot_layout(fig)
    st.plotly_chart(fig,use_container_width=True)
    chart_note("💡 Understanding category contribution helps prioritize inventory and product strategies.")

with col2:
    section_header("💰 Revenue by Category")
    chart_label("📌 Revenue generated by each product category.")
    category_revenue=df.groupby("category")["Revenue"].sum().reset_index()
    fig=px.bar(category_revenue,x="category",y="Revenue",color="Revenue")
    apply_plot_layout(fig)
    st.plotly_chart(fig,use_container_width=True)
    chart_note("💡 Identifying top-performing categories helps maximize profitability and resource allocation.")

# ==========================
# TOP PRODUCTS
# ==========================

section_header("🏆 Top 10 Products")
chart_label("📌 Products generating the highest revenue.")
top_products=df.groupby("product_name")["Revenue"].sum().sort_values(ascending=False).head(10).reset_index()
fig=px.bar(top_products,x="Revenue",y="product_name",orientation="h",color="Revenue")
apply_plot_layout(fig)
st.plotly_chart(fig,use_container_width=True)
chart_note("💡 Top-performing products contribute significantly to revenue and should be prioritized for inventory availability.")

# ==========================
# SALES SUMMARY TABLE
# ==========================

section_header("📋 Sales Summary Table")
chart_label("📌 Detailed revenue and sales performance by product.")
sales_table=df.groupby(["product_name","category"]).agg(Units_Sold=("quantity_sold","sum"),Revenue=("Revenue","sum"),Avg_Price=("unit_price","mean")).reset_index().sort_values("Revenue",ascending=False)
sales_table=sales_table.rename(columns={"product_name":"📦 Product","category":"🏷️ Category","Units_Sold":"📊 Units Sold","Revenue":"💰 Revenue","Avg_Price":"💲 Avg Price"})
st.dataframe(sales_table,use_container_width=True,hide_index=True)
chart_note("💡 Compare product-level sales and revenue performance to identify growth opportunities.")

# ==========================
# BUSINESS INSIGHTS
# ==========================

section_header("🏢 Business Insights")
top_category=df.groupby("category")["Revenue"].sum().idxmax()
top_category_revenue=df.groupby("category")["Revenue"].sum().max()
top_product=df.groupby("product_name")["Revenue"].sum().idxmax()
top_product_revenue=df.groupby("product_name")["Revenue"].sum().max()
best_sales_day=revenue_trend.loc[revenue_trend["Revenue"].idxmax(),"transaction_date"]
best_sales_revenue=revenue_trend["Revenue"].max()

insight_card(f"💰 Highest Revenue Category: {top_category}<br><small>Revenue: ${top_category_revenue:,.0f}</small>",kind="success")
insight_card(f"🏆 Best Performing Product: {top_product}<br><small>Revenue: ${top_product_revenue:,.0f}</small>",kind="success")
insight_card(f"📅 Best Sales Day: {best_sales_day.date()}<br><small>Revenue: ${best_sales_revenue:,.0f}</small>",kind="info")
insight_card(f"🛒 Total Transactions: {summary['Total Transactions']:,}<br><small>Avg Order Value: ${summary['Average Order Value']:,.2f}</small>",kind="info")
insight_card("🎯 Focus inventory planning, pricing strategy, and promotional campaigns around top-performing products and categories to maximize revenue growth.",kind="warning")
