import streamlit as st
import pandas as pd
import plotly.express as px
from style import *
from utils import *

# ==========================
# PAGE CONFIG
# ==========================

st.set_page_config(
    page_title="Customer Analytics",
    page_icon="👥",
    layout="wide",
    initial_sidebar_state="expanded")

# ==========================
# STYLE
# ==========================

inject_css()
sidebar_brand()

# ==========================
# LOAD DATA
# ==========================

@st.cache_data
def load_data():
    df = pd.read_csv("data/Walmart.csv")
    df["transaction_date"] = pd.to_datetime(df["transaction_date"])
    return df

df = load_data()
df=sidebar_filters(df)
# Revenue Column
df["Revenue"] = (df["quantity_sold"] *df["unit_price"])

# ==========================
# PAGE HEADER
# ==========================

page_header("👨🏻 Customer Analysis","Analyze customer demographics, loyalty behavior and spending pattern.")

# ==========================
# KPI SECTION
# ==========================

total_customers = df["customer_id"].nunique()
avg_age = round(df["customer_age"].mean(),1)
avg_income = round(df["customer_income"].mean())
top_loyalty = df["customer_loyalty_level"].mode()[0]

c1, c2, c3, c4 = st.columns(4)
kpi_card(c1,"👨🏻 Total Customers",f"{total_customers} Customers",color="red")
kpi_card(c2,"🎂 Average Age",f"{avg_age:,.0f} Age",color="green")
kpi_card(c3,"💰 Average Income",f"${avg_income}",color="cyan")
kpi_card(c4,"⭐ Top Loyalty Level",top_loyalty,color="blue")

# ==========================
# GENDER ANALYSIS
# ==========================

c1, c2 = st.columns(2)
with c1:
    section_header("👥 Gender Distribution")
    chart_label("📌 Distribution of customers across different genders.")
    gender_dist = df["customer_gender"].value_counts().reset_index()
    gender_dist.columns = ["Gender","Count"]
    fig = px.pie(gender_dist,names="Gender",values="Count")
    apply_plot_layout(fig)
    st.plotly_chart(fig,use_container_width=True)
    chart_note( "💡 The customer base is distributed across genders, helping identify the primary audience and supporting targeted marketing strategies.")

with c2:
    section_header("💰 Revenue by Gender")
    chart_label("📌 Total revenue contribution by customer gender.")
    gender_revenue = df.groupby("customer_gender")["Revenue"].sum().reset_index()
    fig = px.bar(gender_revenue,x="customer_gender",y="Revenue",color="customer_gender")
    fig.update_xaxes(title="Gender")
    fig.update_yaxes(title="Revenue")
    apply_plot_layout(fig)
    st.plotly_chart(fig,use_container_width=True)
    chart_note("💡 Comparing revenue across genders helps identify the most valuable customer groups and optimize customer acquisition efforts.")

# ===================================
# AGE DISTRIBUTION & INCOME ANALYSIS
# ===================================

c3, c4 = st.columns(2)
with c3:
    section_header("🎂 Age Distribution")
    chart_label("📌 Distribution of customers across different age groups.")
    fig = px.histogram(df,x="customer_age",color_discrete_sequence=["orange"])
    fig.update_traces(marker_line_color="black",marker_line_width=1.5)
    apply_plot_layout(fig)
    st.plotly_chart(fig,use_container_width=True)
    chart_note("💡 Age patterns reveal the dominant customer demographic, enabling age-specific product recommendations and campaigns.")

with c4:
    section_header("💰 Income Analysis")
    chart_label("📌 Relationship between customer income and generated revenue.")
    gender_income = df.groupby("customer_income")["Revenue"].sum().reset_index()
    fig = px.scatter(gender_income,x="customer_income",y="Revenue")
    fig.update_xaxes(title="Customer Income")
    fig.update_yaxes(title="Revenue")
    apply_plot_layout(fig)
    st.plotly_chart(fig,use_container_width=True)
    chart_note("💡 Higher-income customers may contribute more revenue, providing opportunities for premium product positioning and upselling.")

# ==========================
# LOYALTY ANALYSIS
# ==========================

c5, c6 = st.columns(2)
with c5:
    section_header("⭐ Loyalty Analysis")
    chart_label("📌 Number of customers across loyalty program levels.")
    loyalty_count = (df["customer_loyalty_level"].value_counts().reset_index())
    loyalty_count.columns = ["Loyalty", "Count"]
    fig = px.bar(loyalty_count,x="Loyalty",y="Count",color="Loyalty")
    fig.update_xaxes(title="Loyalty Level")
    fig.update_yaxes(title="Number of Customers")
    apply_plot_layout(fig)
    st.plotly_chart(fig, use_container_width=True)
    chart_note("💡 Understanding loyalty distribution helps evaluate customer retention performance and identify opportunities for engagement.")

with c6:
    section_header("💸 Revenue by Loyalty Level")
    chart_label("📌 Revenue generated by each customer loyalty segment.")
    loyalty_revenue = (df.groupby("customer_loyalty_level")["Revenue"].sum().reset_index())
    fig = px.bar(loyalty_revenue,x="customer_loyalty_level",y="Revenue",color="customer_loyalty_level")
    fig.update_xaxes(title="Loyalty Level")
    fig.update_yaxes(title="Number of Customers")
    apply_plot_layout(fig)
    st.plotly_chart(fig, use_container_width=True)
    chart_note("💡 Loyal customers often contribute significantly more revenue, highlighting the importance of retention and rewards programs.")

# ==========================
# PAYMENT METHOD ANALYSIS
# ==========================

c7, c8 =st.columns(2)
with c7:
    section_header("💳 Payment Method Analysis")
    chart_label("📌 Revenue contribution by payment method.")
    payment = df.groupby("payment_method")["Revenue"].sum().reset_index()
    fig = px.pie(payment,names="payment_method",values="Revenue")
    apply_plot_layout(fig)
    st.plotly_chart(fig,use_container_width=True)
    chart_note("💡 Customer payment preferences can guide checkout optimization and promotional offers for preferred payment channels.")

# ==========================
# TOP CUSTOMER SEGMENTS
# ==========================

with c8:
    section_header("🏆 Top Customer Segment")
    chart_label("📌 Revenue and transaction performance across customer gender and loyalty segments.")
    segment_table = df.groupby(["customer_gender","customer_loyalty_level"]).agg(Revenue=("Revenue","sum"),
        Transactions=("transaction_id","count")).reset_index().sort_values("Revenue",ascending=False)
    segment_table = segment_table.rename(columns={"customer_gender": "👨🏻 Customer Gender","customer_loyalty_level": "⭐ Loyalty Level",
    "Revenue": "💰 Total Revenue ($)","Transactions": "🛒 Transactions"})
    st.dataframe(segment_table,use_container_width=True,hide_index=True)
    chart_note("💡 Identifying the highest-performing customer segments enables targeted marketing, personalized campaigns, and improved customer lifetime value.")

# ==========================
# INSIGHTS
# ==========================

section_header("👥 Customer Insights")
best_loyalty_data = (df.groupby("customer_loyalty_level")["Revenue"].sum().sort_values(ascending=False))
best_loyalty = best_loyalty_data.index[0]
best_loyalty_revenue = best_loyalty_data.iloc[0]
best_payment_data = (df.groupby("payment_method")["Revenue"].sum().sort_values(ascending=False))
best_payment = best_payment_data.index[0]
best_payment_revenue = best_payment_data.iloc[0]
insight_card(f"🏆 Highest Revenue Loyalty Segment: {best_loyalty}<br><small>Revenue: ₹{best_loyalty_revenue:,.2f}</small>",kind="success")
insight_card(f"💳 Top Revenue Payment Method: {best_payment}<br><small>Revenue: ₹{best_payment_revenue:,.2f}</small>",kind="success")
insight_card("👥 Customer demographics reveal distinct purchasing behaviors across loyalty segments.",kind="info")
insight_card("🎯 Prioritize retention campaigns for high-value customers and personalize offers based on preferred payment methods.",kind="warning")