import streamlit as st
import pandas as pd
import plotly.express as px
from style import *
from utils import *

# ==========================
# PAGE CONFIG
# ==========================

st.set_page_config(
    page_title="Promotion Analytics",
    page_icon="📢",
    layout="wide",
    initial_sidebar_state="expanded")

# ==========================
# STYLE
# ==========================

inject_css()
sidebar_brand()

# ==========================
# LOAD DATA
# ==========================

@st.cache_data
def load_data():
    df = pd.read_csv("data/Walmart.csv")
    df["transaction_date"] = pd.to_datetime(df["transaction_date"])
    return df

df = load_data()
df=sidebar_filters(df)
# Revenue Column
df["Revenue"] = (
    df["quantity_sold"] *
    df["unit_price"]
)

# ==========================
# PAGE HEADER
# ==========================

page_header("Promotion Analysis","Analyze promotion effectiveness, demand uplift and revenue impact.")

# ==========================
# KPI SECTION
# ==========================

promo_revenue = df[df["promotion_applied"]==1]["Revenue"].sum()
non_promo_revenue = df[df["promotion_applied"]==0]["Revenue"].sum()
promotion_rate = df["promotion_applied"].mean()*100
avg_promo_demand = df[df["promotion_applied"]==1]["actual_demand"].mean()

c1, c2, c3, c4 = st.columns(4)
kpi_card(c1,"🔊 Promotion Usage %",f"{promotion_rate:.1f}%",color="yellow")
kpi_card(c2,"💰 Promo Revenue",f"${promo_revenue:,.0f}",color="cyan")
kpi_card(c3,"📉 Non Promo Revenue",f"{non_promo_revenue:.1f}",color="red")
kpi_card(c4,"📈 Avgerage Promo Demand",f"{avg_promo_demand:.1f}",color="green")

# ==========================
# PROMOTION VS NON-PROMOTION
# ==========================

c1, c2 = st.columns(2)
with c1:
    section_header("📊 Promotion vs Non Promotion Revenue")
    chart_label("📌 Comparison of total revenue generated with and without promotional campaigns.")
    promo_compare = df.groupby("promotion_applied")["Revenue"].sum().reset_index()
    promo_compare["promotion_applied"] = promo_compare["promotion_applied"].map({True: "Promotion",False: "No Promotion"})
    fig = px.bar(promo_compare,x="promotion_applied",y="Revenue",color="Revenue")
    apply_plot_layout(fig)
    st.plotly_chart(fig,use_container_width=True)
    chart_note("💡 Promotions can significantly influence sales performance. Comparing promotional and non-promotional revenue helps measure campaign effectiveness.")

# ==========================
# PROMOTION TYPE ANALYSIS
# ==========================

with c2:
    section_header("🎯 Promotion Type Performance")
    chart_label("📌 Revenue generated by each promotion type.")
    promotion_type = df.groupby("promotion_type").agg(Revenue=("Revenue","sum"),Demand=("actual_demand","mean")).reset_index()
    fig = px.bar(promotion_type,x="promotion_type",y="Revenue",color="Revenue")
    apply_plot_layout(fig)
    st.plotly_chart(fig,use_container_width=True)
    chart_note("💡 Identifying the highest-performing promotion types enables better allocation of marketing budgets and campaign planning.")

# ==========================
# DEMAND IMPACT
# ==========================

c3, c4 = st.columns(2)
with c3:
    section_header("📈 Promotion Impact on Demand")
    chart_label("📌 Average customer demand during promotional and non-promotional periods.")
    demand_df = df.groupby("promotion_applied")["actual_demand"].mean().reset_index()
    demand_df["promotion_applied"] = demand_df["promotion_applied"].map({True: "Promotion",False: "No Promotion"})
    fig = px.bar(demand_df,x="promotion_applied",y="actual_demand",color="promotion_applied")
    apply_plot_layout(fig)
    st.plotly_chart(fig,use_container_width=True)
    chart_note("💡 Increased demand during promotional periods indicates successful customer engagement and campaign effectiveness.")

# ==========================
# PROMOTION TREND
# ==========================

with c4:
    section_header("📅 Promotion Revenue Trend")
    chart_label("📌 Revenue trend generated from promotional campaigns over time.")
    promo_trend = df[df["promotion_applied"]==1].groupby("transaction_date")["Revenue"].sum().reset_index()
    fig = px.line(promo_trend,x="transaction_date",y="Revenue")
    apply_plot_layout(fig)
    st.plotly_chart(fig,use_container_width=True)
    chart_note("💡 Tracking promotional revenue trends helps identify peak-performing periods and optimize campaign scheduling.")

# ==========================
# HOLIDAY ANALYSIS
# ==========================

c5, c6 = st.columns(2)
with c5:
    section_header("🎉 Holiday Promotion Performance")
    chart_label("📌 Revenue performance during holiday and non-holiday periods.")
    holiday_df = df.groupby("holiday_indicator").agg(Revenue=("Revenue","sum"),Demand=("actual_demand","mean")).reset_index()
    holiday_df["holiday_indicator"] = holiday_df["holiday_indicator"].map({False:"Non-Hoilday",True:"Holiday"})
    fig = px.bar(holiday_df,x="holiday_indicator",y="Revenue",color="Revenue")
    apply_plot_layout(fig)
    st.plotly_chart(fig,use_container_width=True)
    chart_note("💡 Holiday periods often generate higher customer demand and revenue, making them critical opportunities for promotional campaigns.")

# ==========================
# LOYALTY RESPONSE
# ==========================

with c6:
    section_header("⭐ Promotion Response by Loyalty Level")
    chart_label("📌 Revenue contribution from different customer loyalty segments.")
    loyalty_level_df = df.groupby("customer_loyalty_level").agg(Revenue=("Revenue","sum")).reset_index()
    fig = px.bar(loyalty_level_df,x="customer_loyalty_level",y="Revenue",color="Revenue")
    apply_plot_layout(fig)
    st.plotly_chart(fig,use_container_width=True)
    chart_note("💡 Loyal customers typically respond more positively to promotions and contribute a larger share of overall revenue.")

# ==========================
# PROMOTION SUMMARY TABLE
# ==========================

section_header("🗒️ Promotion Performance Table")
chart_label("📌 Detailed performance metrics for each promotion type.")
promotion_table = (df.groupby("promotion_type").agg(Revenue=("Revenue", "sum"),Avg_Demand=("actual_demand", "mean"),Transactions=("transaction_id", "count"))
    .reset_index().sort_values("Revenue", ascending=False))
promotion_table = promotion_table.rename(columns={
    "promotion_type": "🎯 Promotion Type",
    "Revenue": "💰 Total Revenue",
    "Avg_Demand": "📈 Avg Demand",
    "Transactions": "🛒 Transactions"
})
st.dataframe(promotion_table,use_container_width=True,hide_index=True)
chart_note("💡 Compare promotion effectiveness using revenue, demand, and transaction volume to identify the most successful campaigns.")

# ==========================
# BUSINESS INSIGHTS
# ==========================

section_header("🏢 Promotion Insights")
promo_revenue = (df.groupby("promotion_type")["Revenue"].sum().sort_values(ascending=False))
best_promo = promo_revenue.index[0]
best_promo_revenue = promo_revenue.iloc[0]
promo_demand = (df[df["promotion_applied"] == 1]["actual_demand"].mean())
normal_demand = (df[df["promotion_applied"] == 0]["actual_demand"].mean())
uplift = ((promo_demand - normal_demand) / normal_demand) * 100

insight_card(f"🏆 Best Performing Promotion: {best_promo}<br><small>Revenue: ₹{best_promo_revenue:,.2f}</small>",kind="success")
insight_card(f"📈 Demand Uplift from Promotions: {uplift:.1f}%",kind="success")
insight_card("💰 Promotional campaigns contribute significantly to revenue growth and customer engagement.",kind="info")
insight_card("🎯 Focus future campaigns on high-performing promotion types and periods with strong demand response.",kind="warning")